  # Trigger action when push and push-request
  workflow_run:
    workflows: ["ReleaseJson"]
    branches:  
      - master
    types: 
      - completed

    # Npm patch version and publish
    - name: Npm init
      uses: actions/checkout@v2
      uses: actions/setup-node@v1
      with:
        node-version: "12.x"
        registry-url: https://registry.npmjs.org/

    - name: npm patch version and publish
      run: |
        npm version patch
        npm publish
      env:
        NODE_AUTH_TOKEN: ${{secrets.npm_token}}

    # Commit json into repo
    - name: Commit
      env:
        $USER_EMAIL: ${{ secrets.USER_EMAIL }}
        $USER_NAME: ${{ secrets.USER_NAME }}
      run: |
        git config --global user.email ${{ secrets.USER_EMAIL }}
        git config --global user.name ${{ secrets.USER_NAME }}
        git add .
        git commit -m "links(json): update YML and generate JSON successfully" -a
    - name: Push changes
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets._GITHUB_TOKEN }}